// vue3/src/components/Board.vue
<template>
  <div>
    <div class="status">{{ status }}</div>
    <div class="board-row">
      <Square :value="squares[0]" @click="handleClick(0)" />
      <Square :value="squares[1]" @click="handleClick(1)" />
      <Square :value="squares[2]" @click="handleClick(2)" />
    </div>
    <div class="board-row">
      <Square :value="squares[3]" @click="handleClick(3)" />
      <Square :value="squares[4]" @click="handleClick(4)" />
      <Square :value="squares[5]" @click="handleClick(5)" />
    </div>
    <div class="board-row">
      <Square :value="squares[6]" @click="handleClick(6)" />
      <Square :value="squares[7]" @click="handleClick(7)" />
      <Square :value="squares[8]" @click="handleClick(8)" />
    </div>
  </div>
</template>

<script setup>
import Square from "./Square.vue";
import { computed } from "vue";

function calculateWinner(squares) {
  const lines = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6],
  ];
  for (let i = 0; i < lines.length; i++) {
    const [a, b, c] = lines[i];
    if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
      return squares[a];
    }
  }
  return null;
}

const props = defineProps({
  xIsNext: Boolean,
  squares: Array,
});

const emit = defineEmits(["play"]);

const status = computed(() => {
  const winner = calculateWinner(props.squares);
  if (winner) {
    return `Winner: ${winner}`;
  } else {
    return `Next player: ${props.xIsNext ? "X" : "O"}`;
  }
});

function handleClick(i) {
  if (calculateWinner(props.squares) || props.squares[i]) {
    return;
  }
  const nextSquares = props.squares.slice();
  if (props.xIsNext) {
    nextSquares[i] = "X";
  } else {
    nextSquares[i] = "O";
  }
  emit("play", nextSquares);
}
</script>

<style scoped></style>

// react18/src/components/Board.jsx
import Square from './Square';

function calculateWinner(squares) {
  const lines = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6],
  ];
  for (let i = 0; i < lines.length; i++) {
    const [a, b, c] = lines[i];
    if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
      return squares[a];
    }
  }
  return null;
}

export default function Board({ xIsNext, squares, onPlay }) {
  function handleClick(i) {
    if (calculateWinner(squares) || squares[i]) {
      return;
    }
    const nextSquares = squares.slice();
    if (xIsNext) {
      nextSquares[i] = 'X';
    } else {
      nextSquares[i] = 'O';
    }
    onPlay(nextSquares);
  }

  const winner = calculateWinner(squares);
  let status;
  if (winner) {
    status = 'Winner: ' + winner;
  } else {
    status = 'Next player: ' + (xIsNext ? 'X' : 'O');
  }

  return (
    <>
      <div className="status">{status}</div>
      <div className="board-row">
        <Square value={squares[0]} onSquareClick={() => handleClick(0)} />
        <Square value={squares[1]} onSquareClick={() => handleClick(1)} />
        <Square value={squares[2]} onSquareClick={() => handleClick(2)} />
      </div>
      <div className="board-row">
        <Square value={squares[3]} onSquareClick={() => handleClick(3)} />
        <Square value={squares[4]} onSquareClick={() => handleClick(4)} />
        <Square value={squares[5]} onSquareClick={() => handleClick(5)} />
      </div>
      <div className="board-row">
        <Square value={squares[6]} onSquareClick={() => handleClick(6)} />
        <Square value={squares[7]} onSquareClick={() => handleClick(7)} />
        <Square value={squares[8]} onSquareClick={() => handleClick(8)} />
      </div>
    </>
  );
}
