// vue2/src/components/Game.vue
<template>
  <div class="game">
    <div class="game-board">
      <Board :xIsNext="xIsNext" :squares="currentSquares" @play="handlePlay" />
    </div>
    <div class="game-info">
      <ol>
        <li v-for="(squares, move) in history" :key="move">
          <button @click="jumpTo(move)">
            {{ move ? `Go to move #${move}` : "Go to game start" }}
          </button>
        </li>
      </ol>
    </div>
  </div>
</template>

<script>
import Board from "./Board.vue";
export default {
  name: "Game",
  components: {
    Board,
  },
  data() {
    return {
      history: [Array(9).fill(null)],
      currentMove: 0,
    };
  },
  computed: {
    xIsNext() {
      return this.currentMove % 2 === 0;
    },
    currentSquares() {
      return this.history[this.currentMove];
    },
  },
  methods: {
    handlePlay(nextSquares) {
      this.history = [
        ...this.history.slice(0, this.currentMove + 1),
        nextSquares,
      ];
      this.currentMove = this.history.length - 1;
    },
    jumpTo(nextMove) {
      this.currentMove = nextMove;
    },
  },
};
</script>

<style scoped></style>

// react18/src/components/Game.jsx
import { useState } from 'react';
import Board from './Board';

export default function Game() {
  const [history, setHistory] = useState([Array(9).fill(null)]);
  const [currentMove, setCurrentMove] = useState(0);
  const xIsNext = currentMove % 2 === 0;
  const currentSquares = history[currentMove];

  function handlePlay(nextSquares) {
    const nextHistory = [...history.slice(0, currentMove + 1), nextSquares];
    setHistory(nextHistory);
    setCurrentMove(nextHistory.length - 1);
  }

  function jumpTo(nextMove) {
    setCurrentMove(nextMove);
  }

  const moves = history.map((squares, move) => {
    let description;
    if (move > 0) {
      description = 'Go to move #' + move;
    } else {
      description = 'Go to game start';
    }
    return (
      <li key={move}>
        <button onClick={() => jumpTo(move)}>{description}</button>
      </li>
    );
  });

  return (
    <div className="game">
      <div className="game-board">
        <Board xIsNext={xIsNext} squares={currentSquares} onPlay={handlePlay} />
      </div>
      <div className="game-info">
        <ol>{moves}</ol>
      </div>
    </div>
  );
}
